### ISSUE TITLE
RealESRGAN CPU support

### ISSUE THREAD

**Issue by hdon1** [hlky/stable-diffusion-webui#81]
RealESRGAN causes GPU out of memory crash at the end of each batch. CPU can run RealESRGAN pretty quickly and without reloading models each batch.

**Comment by hlky** [comment]
Should be working, please test and report back

**Comment by hlky** [comment]
default prompt default settings except steps=10

![00267-3043153027_](https://user-images.githubusercontent.com/106811348/186987006-a91ec3b5-8736-46fc-ba1e-6a3492ba6c97.jpg)

upscale tab own image (previous img2img result)
![download](https://user-images.githubusercontent.com/106811348/186987167-06d3b503-170c-41b8-9c8e-df46b4278c17.png)

original
![00003-4174364878_An_owl_perched_on_a_branch,_high-quality,_Pixiv,_Greg_Rutkowski,_ArtStation,_Oil_on_canvas](https://user-images.githubusercontent.com/106811348/186987237-161e764b-f591-4fad-9768-e37dc2a22d2e.png)

**Comment by hdon1** [comment]
For some reason it is working fine on GPU now... (1080 ti)

**Comment by hlky** [comment]
python vs c#
what cpu do you have? that's probably the issue, it didn't take long for me with Xeon E5-2630v2


> For some reason it is working fine on GPU now... (1080 ti)

as in you switched back to master and it's now working on gpu?
